apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vane.fullname" . }}
  labels:
    app: {{ include "vane.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "vane.name" . }}
  template:
    metadata:
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
      labels:
        app: {{ include "vane.name" . }}
    spec:
      containers:
        - name: vane
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: ["run", "-c", "/etc/vane/vane.toml"]
          ports:
            - containerPort: 8080
              name: ingress
            - containerPort: {{ .Values.admin.port }}
              name: admin
          resources:
{{ toYaml .Values.resources | indent 12 }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: admin
          livenessProbe:
            httpGet:
              path: /healthz
              port: admin
          volumeMounts:
            - name: config
              mountPath: /etc/vane
          {{- if .Values.sidecar.enabled }}
            - name: sidecar-shm
              mountPath: /dev/shm
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "vane.fullname" . }}
        {{- if .Values.sidecar.enabled }}
        - name: sidecar-shm
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.sidecar.shmSize }}
        {{- end }}
