apiVersion: v1
kind: Service
metadata:
  name: {{ include "vane.fullname" . }}
  labels:
    app: {{ include "vane.name" . }}
spec:
  selector:
    app: {{ include "vane.name" . }}
  ports:
    - name: ingress
      port: 80
      targetPort: 8080
    - name: admin
      port: {{ .Values.admin.port }}
      targetPort: admin
