apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vane.fullname" . }}
  labels:
    {{- include "vane.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "vane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vane.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.prometheus }}
        {{- if .enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ $.Values.service.adminPort | quote }}
        prometheus.io/path: "/metrics"
        {{- end }}
        {{- end }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.k8sProvider.enabled }}
      serviceAccountName: {{ include "vane.serviceAccountName" . }}
      {{- end }}
      containers:
        - name: vane
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["run", "-c", "/etc/vane/vane.toml"]
          ports:
            - name: data
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            {{- if .Values.admin.enabled }}
            - name: admin
              containerPort: {{ .Values.service.adminPort }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: admin
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: admin
            initialDelaySeconds: 3
            periodSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /etc/vane
              readOnly: true
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "vane.fullname" . }}-config
