//! In-process HTTP/3 upstream bridge (feature `h3`) — the milestone-4
//! integration (docs/h3-design.md).
//!
//! The engine's synchronous workers dial a loopback TCP listener and
//! speak plain HTTP/1.1, exactly as they would with any other
//! backend; this bridge re-originates each request over QUIC/HTTP-3
//! to the cluster's real backends and translates the response back to
//! h1. The worker needs no knowledge of QUIC.
//!
//! Architecture: the bridge's h3 engine runs on ONE dedicated thread
//! hosting a current-thread tokio runtime. It owns a shared
//! `quinn::Endpoint` and a per-backend connection pool — one QUIC
//! handshake per backend, requests multiplex as h3 streams. The h1
//! side (thread-per-connection) hands each parsed request to the
//! engine over a channel and blocks on the response.
//!
//! Health: the engine owns backend health for the cluster. Active
//! probes (`health_path`) plus active-failure feedback mark backends
//! down; round-robin picks among healthy backends, with one in-bridge
//! retry on the next healthy backend. This covers what the engine
//! cannot see past the loopback address (its health probes, outlier
//! ejection, and breaker all apply to the bridge itself).
//!
//! Failure semantics: when no backend answers, the h1 socket closes
//! abruptly — the worker sees premature EOF and the existing failover
//! rules treat it like any dead backend.

use std::collections::HashMap;
use std::io::{Read, Write};
use std::net::SocketAddr;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::{Arc, Mutex};
use std::time::Duration;

use tokio::sync::{mpsc, oneshot};
use vane_control::config::H3UpstreamTls;

/// Head/body read cap for the loopback h1 side (the engine only ever
/// sends bounded requests).
const MAX_HEAD: usize = 64 * 1024;
const MAX_BODY: usize = 32 * 1024 * 1024;

/// Bridge tuning beyond the TLS material.
#[derive(Clone)]
pub struct BridgeOptions {
    /// Whole-exchange timeout (dial + head + body) — mirrors the
    /// engine's first-byte deadline.
    pub first_byte_timeout: Duration,
    /// Active health-check path; `None` disables proactive probing
    /// (reactive marking on request failure still applies).
    pub health_path: Option<String>,
    /// Interval between active health probes.
    pub probe_interval: Duration,
    /// Cluster name for metric labels.
    pub cluster: String,
    /// Metrics registry (`None` = no bridge metrics — tests).
    pub registry: Option<Arc<vane_observe::metrics::Registry>>,
}

impl Default for BridgeOptions {
    fn default() -> Self {
        Self {
            first_byte_timeout: Duration::from_secs(10),
            health_path: None,
            probe_interval: Duration::from_secs(5),
            cluster: "default".to_string(),
            registry: None,
        }
    }
}

/// Registered metric handles (all optional — tests run without a
/// registry).
#[derive(Default)]
struct BridgeMetrics {
    registry: Option<Arc<vane_observe::metrics::Registry>>,
    backend_healthy: Vec<Option<vane_observe::metrics::MetricHandle>>,
    rotations: Option<vane_observe::metrics::MetricHandle>,
    handshake_failures: Vec<Option<vane_observe::metrics::MetricHandle>>,
    requests_ok: Option<vane_observe::metrics::MetricHandle>,
    requests_error: Option<vane_observe::metrics::MetricHandle>,
}

/// One request handed from the h1 side to the h3 engine.
struct Job {
    method: String,
    path: String,
    authority: String,
    body: Vec<u8>,
    /// Vane-to-vane identity headers (verified upstream-side, never
    /// generated by clients): forwarded verbatim so chains survive
    /// bridge hops.
    identity: Vec<(&'static str, String)>,
    respond: oneshot::Sender<Result<crate::h3_client::H3Response, String>>,
}

/// Pooled h3 connection to one backend.
struct Pooled {
    send: crate::h3_client::H3SendRequest,
}

/// Engine state shared by the job handler and the prober.
struct Engine {
    cfg: crate::h3_client::H3ClientConfig,
    /// Endpoint handle behind a lock: the reloader swaps the default
    /// client config on rotation; dialers clone the handle fresh per
    /// attempt so new dials pick up rotated material.
    endpoint: Mutex<quinn::Endpoint>,
    /// Raw upstream material paths — re-read when the files change
    /// (SVID rotation) and swapped onto the live endpoint.
    tls: Option<H3UpstreamTls>,
    backends: Vec<SocketAddr>,
    /// Healthy mask (parallel to `backends`).
    healthy: Mutex<Vec<bool>>,
    /// Round-robin cursor.
    rr: AtomicUsize,
    pool: Mutex<HashMap<SocketAddr, Pooled>>,
    opts: BridgeOptions,
    metrics: BridgeMetrics,
}

impl Engine {
    fn mark(&self, idx: usize, healthy: bool) {
        {
            let mut h = self.healthy.lock().expect("health lock");
            h[idx] = healthy;
        }
        if let (Some(reg), Some(Some(g))) = (
            &self.metrics.registry,
            self.metrics.backend_healthy.get(idx),
        ) {
            g.set(reg, u64::from(healthy));
        }
    }

    /// A pooled h3 client for `addr`, dialing on miss (or after an
    /// eviction). The driver task is spawned once per connection.
    async fn pooled(&self, addr: SocketAddr) -> Result<crate::h3_client::H3SendRequest, String> {
        if let Some(p) = self.pool.lock().expect("pool lock").get(&addr) {
            return Ok(p.send.clone());
        }
        let endpoint = self.endpoint.lock().expect("endpoint lock").clone();
        let connecting = endpoint
            .connect(addr, &self.cfg.server_name)
            .map_err(|e| format!("connect: {e}"))?;
        let quinn_conn = match tokio::time::timeout(self.opts.first_byte_timeout, connecting).await
        {
            Ok(Ok(c)) => c,
            Ok(Err(e)) => {
                self.count_handshake_failure(&addr);
                return Err(format!("quinn connect: {e}"));
            }
            Err(_) => {
                self.count_handshake_failure(&addr);
                return Err("quinn connect timed out".into());
            }
        };
        let (mut driver, send) = crate::h3_client::client_new(quinn_conn).await?;
        tokio::spawn(async move {
            let err = driver.wait_idle().await;
            tracing::trace!("h3 bridge: connection driver idle: {err:?}");
        });
        self.pool
            .lock()
            .expect("pool lock")
            .insert(addr, Pooled { send: send.clone() });
        Ok(send)
    }

    fn evict(&self, addr: SocketAddr) {
        self.pool.lock().expect("pool lock").remove(&addr);
    }

    fn count_handshake_failure(&self, addr: &SocketAddr) {
        if let (Some(reg), Some(Some(f))) = (
            &self.metrics.registry,
            self.metrics.handshake_failures.get(
                self.backends
                    .iter()
                    .position(|b| b == addr)
                    .unwrap_or(usize::MAX),
            ),
        ) {
            f.inc(reg);
        }
    }

    fn count_request(&self, ok: bool) {
        if let Some(reg) = &self.metrics.registry {
            let h = if ok {
                self.metrics.requests_ok.as_ref()
            } else {
                self.metrics.requests_error.as_ref()
            };
            if let Some(h) = h {
                h.inc(reg);
            }
        }
    }

    /// One full attempt against a specific backend.
    async fn attempt(
        self: &Arc<Self>,
        idx: usize,
        addr: SocketAddr,
        job: &Job,
    ) -> Result<crate::h3_client::H3Response, String> {
        let mut send = match self.pooled(addr).await {
            Ok(s) => s,
            Err(e) => {
                self.evict(addr);
                self.mark(idx, false);
                return Err(e);
            }
        };
        let fut = crate::h3_client::exchange(
            &mut send,
            &job.method,
            &job.path,
            &job.authority,
            &job.body,
            &job.identity,
        );
        match tokio::time::timeout(self.opts.first_byte_timeout, fut).await {
            Ok(Ok(resp)) => Ok(resp),
            Ok(Err(e)) => {
                // Broken pooled connection: evict and mark down.
                self.evict(addr);
                self.mark(idx, false);
                Err(e)
            }
            Err(_) => {
                self.evict(addr);
                self.mark(idx, false);
                Err("h3 exchange timed out".into())
            }
        }
    }

    /// Serves one job: pick a healthy backend, exchange, retry once on
    /// the next healthy backend.
    async fn handle(self: &Arc<Self>, job: Job) {
        let mut attempts = 0usize;
        let mut tried: Vec<usize> = Vec::new();
        let max_attempts = 2usize;
        while let Some((idx, addr)) = (|| {
            let healthy = self.healthy.lock().expect("health lock");
            let start = self.rr.fetch_add(1, Ordering::Relaxed) % self.backends.len();
            for i in 0..self.backends.len() {
                let idx = (start + i) % self.backends.len();
                if healthy[idx] && !tried.contains(&idx) {
                    return Some((idx, self.backends[idx]));
                }
            }
            // Fall back to any untried backend (feed health).
            for i in 0..self.backends.len() {
                let idx = (start + i) % self.backends.len();
                if !tried.contains(&idx) {
                    return Some((idx, self.backends[idx]));
                }
            }
            None
        })() {
            tried.push(idx);
            attempts += 1;
            match self.attempt(idx, addr, &job).await {
                Ok(resp) => {
                    self.count_request(true);
                    let _ = job.respond.send(Ok(resp));
                    return;
                }
                Err(e) => {
                    tracing::debug!(%addr, method = %job.method, path = %job.path,
                        "h3 bridge: attempt failed: {e}");
                    if attempts >= max_attempts {
                        let _ = job.respond.send(Err(e));
                        return;
                    }
                }
            }
        }
        self.count_request(false);
        let _ = job.respond.send(Err("h3 bridge: no backends".into()));
    }
}

/// Spawns the bridge: an ephemeral loopback TCP listener (the engine's
/// backend address) plus the h3 engine thread (shared endpoint, pool,
/// health). Returns the address the engine should use as the cluster's
/// (single) backend.
///
/// # Errors
/// Listener bind or TLS material load failures.
pub fn spawn(
    backends: Vec<SocketAddr>,
    tls: Option<H3UpstreamTls>,
    opts: BridgeOptions,
) -> Result<SocketAddr, String> {
    use vane_observe::metrics::MetricKind;
    let metrics = if let Some(reg) = &opts.registry {
        let label = |name: &str, backend: Option<&SocketAddr>| -> String {
            match backend {
                Some(b) => format!(
                    "{}{{cluster=\"{}\",backend=\"{}\"}}",
                    name,
                    opts.cluster,
                    crate::h3_bridge::sanitize_label(&b.to_string())
                ),
                None => format!("{}{{cluster=\"{}\"}}", name, opts.cluster),
            }
        };
        BridgeMetrics {
            registry: Some(Arc::clone(reg)),
            backend_healthy: backends
                .iter()
                .map(|b| {
                    Some(reg.register(
                        &label("vane_bridge_backend_healthy", Some(b)),
                        MetricKind::Gauge,
                    ))
                })
                .collect(),
            rotations: Some(reg.register(
                &label("vane_bridge_rotations_total", None),
                MetricKind::Counter,
            )),
            handshake_failures: backends
                .iter()
                .map(|b| {
                    Some(reg.register(
                        &label("vane_bridge_handshake_failures_total", Some(b)),
                        MetricKind::Counter,
                    ))
                })
                .collect(),
            requests_ok: Some(reg.register(
                &label("vane_bridge_requests_total_ok", None),
                MetricKind::Counter,
            )),
            requests_error: Some(reg.register(
                &label("vane_bridge_requests_total_error", None),
                MetricKind::Counter,
            )),
        }
    } else {
        BridgeMetrics::default()
    };
    if let Some(reg) = &opts.registry {
        for g in metrics.backend_healthy.iter().flatten() {
            g.set(reg, 1); // optimistic start, matching the mask
        }
    }
    if backends.is_empty() {
        return Err("no backends".into());
    }
    let cfg = build_client_config(tls.as_ref())?;
    let listener = std::net::TcpListener::bind("127.0.0.1:0").map_err(|e| format!("bind: {e}"))?;
    let addr = listener.local_addr().map_err(|e| format!("addr: {e}"))?;
    let (tx, rx) = mpsc::channel::<Job>(256);

    // h3 engine thread: the shared endpoint, connection pool, and
    // health prober all live on this runtime (quinn endpoints bind to
    // the runtime that created them — do not hoist this out).
    let engine_backends = backends.clone();
    let engine_opts = opts.clone();
    std::thread::Builder::new()
        .name("vane-h3-bridge".into())
        .spawn(move || {
            let rt = tokio::runtime::Builder::new_current_thread()
                .enable_all()
                .build()
                .expect("h3 bridge runtime");
            rt.block_on(async move {
                let endpoint =
                    match crate::h3_client::client_endpoint(&cfg, engine_opts.first_byte_timeout) {
                        Ok(e) => e,
                        Err(e) => {
                            tracing::error!("h3 bridge: client endpoint: {e}");
                            return;
                        }
                    };
                let engine = Arc::new(Engine {
                    cfg,
                    endpoint: Mutex::new(endpoint),
                    tls,
                    healthy: Mutex::new(vec![true; engine_backends.len()]),
                    backends: engine_backends,
                    rr: AtomicUsize::new(0),
                    pool: Mutex::new(HashMap::new()),
                    opts: engine_opts,
                    metrics,
                });
                // Upstream-material reloader (SVID rotation): fingerprint
                // the files; on change rebuild the QUIC client config and
                // swap it onto the live endpoint, evicting the pool so
                // the next request re-handshakes with fresh material.
                let reloader = Arc::clone(&engine);
                tokio::spawn(async move {
                    let mut last = material_stamp(reloader.tls.as_ref());
                    loop {
                        tokio::time::sleep(Duration::from_secs(1)).await;
                        let cur = material_stamp(reloader.tls.as_ref());
                        if cur == last {
                            continue;
                        }
                        match build_client_config(reloader.tls.as_ref()).and_then(|c| {
                            crate::h3_client::client_config(&c, reloader.opts.first_byte_timeout)
                        }) {
                            Ok(qcfg) => {
                                reloader
                                    .endpoint
                                    .lock()
                                    .expect("endpoint lock")
                                    .set_default_client_config(qcfg);
                                reloader.pool.lock().expect("pool lock").clear();
                                if let (Some(reg), Some(r)) = (
                                    &reloader.metrics.registry,
                                    reloader.metrics.rotations.as_ref(),
                                ) {
                                    r.inc(reg);
                                }
                                tracing::info!(
                                    "h3 bridge: upstream material rotated — pool re-handshakes"
                                );
                                last = cur;
                            }
                            Err(e) => {
                                tracing::warn!(
                                    "h3 bridge: material reload failed (keeping previous): {e}"
                                );
                                last = cur; // don't spin on a broken file
                            }
                        }
                    }
                });
                // Active health prober.
                if engine.opts.health_path.is_some() {
                    let prober = Arc::clone(&engine);
                    tokio::spawn(async move {
                        loop {
                            tokio::time::sleep(prober.opts.probe_interval).await;
                            probe_once(&prober).await;
                        }
                    });
                }
                // Job loop.
                let mut rx = rx;
                while let Some(job) = rx.recv().await {
                    let e = Arc::clone(&engine);
                    tokio::spawn(async move { e.handle(job).await });
                }
            });
        })
        .map_err(|e| format!("bridge thread: {e}"))?;

    // h1 accept loop: thread-per-connection (sync side).
    std::thread::Builder::new()
        .name("vane-h3-bridge-accept".into())
        .spawn(move || {
            for stream in listener.incoming() {
                match stream {
                    Ok(sock) => {
                        let tx = tx.clone();
                        let opts = opts.clone();
                        let _ = std::thread::Builder::new()
                            .name("vane-h3-bridge-conn".into())
                            .spawn(move || handle_conn(sock, tx, &opts));
                    }
                    Err(e) => {
                        tracing::debug!("h3 bridge accept: {e}");
                    }
                }
            }
        })
        .map_err(|e| format!("bridge accept thread: {e}"))?;
    Ok(addr)
}

/// One active health probe across all backends.
async fn probe_once(engine: &Arc<Engine>) {
    let Some(path) = engine.opts.health_path.clone() else {
        return;
    };
    for (idx, &addr) in engine.backends.iter().enumerate() {
        let mut send = match engine.pooled(addr).await {
            Ok(s) => s,
            Err(e) => {
                tracing::debug!(%addr, "h3 bridge: probe dial failed: {e}");
                engine.mark(idx, false);
                continue;
            }
        };
        let fut =
            crate::h3_client::exchange(&mut send, "GET", &path, &engine.cfg.server_name, &[], &[]);
        let timeout = engine.opts.first_byte_timeout.min(Duration::from_secs(3));
        match tokio::time::timeout(timeout, fut).await {
            Ok(Ok(resp)) if resp.status < 500 => engine.mark(idx, true),
            Ok(Ok(resp)) => {
                engine.mark(idx, false);
                tracing::debug!(%addr, status = resp.status, "h3 bridge: probe unhealthy");
            }
            Ok(Err(e)) => {
                engine.evict(addr);
                engine.mark(idx, false);
                tracing::debug!(%addr, "h3 bridge: probe failed: {e}");
            }
            Err(_) => {
                engine.evict(addr);
                engine.mark(idx, false);
                tracing::debug!(%addr, "h3 bridge: probe timed out");
            }
        }
    }
}

/// Serves one loopback h1 connection: parse the request (single
/// request per connection — the engine's pool opens fresh upstream
/// connections for relay), hand it to the h3 engine, translate the
/// response back.
fn handle_conn(mut sock: std::net::TcpStream, jobs: mpsc::Sender<Job>, opts: &BridgeOptions) {
    let _ = sock.set_read_timeout(Some(opts.first_byte_timeout.max(Duration::from_secs(1))));
    let _ = sock.set_nodelay(true);

    let mut buf = Vec::with_capacity(4096);
    let mut chunk = [0u8; 4096];

    loop {
        // Read the head (one `httparse::Request` parse yields method,
        // path, and headers).
        let (head_len, method, path, headers) = loop {
            if buf.len() > MAX_HEAD {
                return; // absurd head: drop
            }
            let mut storage = [httparse::EMPTY_HEADER; 64];
            let mut req = httparse::Request::new(&mut storage);
            match req.parse(&buf) {
                Ok(httparse::Status::Complete(n)) => {
                    let (method, path) = match (req.method, req.path) {
                        (Some(m), Some(p)) => (m.to_owned(), p.to_owned()),
                        _ => return,
                    };
                    // Own the headers: `buf` is drained between
                    // keep-alive requests.
                    let headers: Vec<(String, Vec<u8>)> = req
                        .headers
                        .iter()
                        .map(|h| (h.name.to_ascii_lowercase(), h.value.to_vec()))
                        .collect();
                    break (n, method, path, headers);
                }
                Ok(httparse::Status::Partial) => {}
                Err(_) => return,
            }
            match sock.read(&mut chunk) {
                Ok(0) => return,
                Ok(n) => buf.extend_from_slice(&chunk[..n]),
                Err(_) => return,
            }
        };

        // Framing: Content-Length only (the engine's h1 relay sends
        // CL or nothing for non-h2 routes; chunked is declined with
        // 501). Keep-alive: honor the client's Connection header.
        let mut content_length: Option<u64> = None;
        let mut chunked = false;
        let mut wants_close = false;
        let mut authority: Option<String> = None;
        // Identity headers from the engine (vane-verified upstream-
        // side); forwarded verbatim through the QUIC hop.
        let mut identity: Vec<(&'static str, String)> = Vec::new();
        for (name, value) in &headers {
            match name.as_str() {
                "content-length" => {
                    content_length = std::str::from_utf8(value)
                        .ok()
                        .and_then(|v| v.trim().parse().ok());
                }
                "transfer-encoding" => chunked = true,
                "host" => authority = std::str::from_utf8(value).ok().map(str::to_owned),
                "connection" => {
                    if let Ok(v) = std::str::from_utf8(value) {
                        wants_close = v.to_ascii_lowercase().contains("close");
                    }
                }
                "x-vane-spiffe-id" => {
                    if let Ok(v) = std::str::from_utf8(value) {
                        identity.push(("x-vane-spiffe-id", v.to_owned()));
                    }
                }
                "x-vane-spiffe-chain" => {
                    if let Ok(v) = std::str::from_utf8(value) {
                        identity.push(("x-vane-spiffe-chain", v.to_owned()));
                    }
                }
                _ => {}
            }
        }
        if chunked {
            let _ = sock.write_all(
                b"HTTP/1.1 501 Not Implemented\r\ncontent-length: 0\r\nconnection: close\r\n\r\n",
            );
            return;
        }
        let cl = content_length.unwrap_or(0);
        if cl > MAX_BODY as u64 {
            return;
        }

        // Read the body.
        let mut body = buf[head_len..].to_vec();
        while body.len() < cl as usize {
            match sock.read(&mut chunk) {
                Ok(0) => return,
                Ok(n) => body.extend_from_slice(&chunk[..n]),
                Err(_) => return,
            }
        }
        body.truncate(cl as usize);
        buf.drain(..head_len + body.len());

        // Hand off to the h3 engine and wait.
        let authority = authority.unwrap_or_else(|| "localhost".to_owned());
        let (rtx, rrx) = oneshot::channel();
        let job = Job {
            method: method.to_owned(),
            path: path.to_owned(),
            authority,
            body,
            identity,
            respond: rtx,
        };
        if jobs.blocking_send(job).is_err() {
            return;
        }
        let Ok(resp) = rrx.blocking_recv() else {
            return; // engine gone: abrupt close
        };
        let resp = match resp {
            Ok(r) => r,
            Err(e) => {
                // h3 failure: abrupt close → worker sees premature EOF
                // and applies its failover rules.
                tracing::debug!(method, path, "h3 bridge: upstream failed: {e}");
                return;
            }
        };

        // Translate to h1. The body is fully buffered, so
        // Content-Length is exact; hop-by-hop and framing headers are
        // dropped. Keep-alive unless the peer asked to close.
        let mut out = Vec::with_capacity(resp.body.len() + 256);
        out.extend_from_slice(
            format!("HTTP/1.1 {} {}\r\n", resp.status, reason(resp.status)).as_bytes(),
        );
        for (n, v) in &resp.headers {
            let ln = String::from_utf8_lossy(n).to_ascii_lowercase();
            if matches!(
                ln.as_str(),
                "transfer-encoding" | "content-length" | "connection" | "keep-alive"
            ) {
                continue;
            }
            out.extend_from_slice(n);
            out.extend_from_slice(b": ");
            out.extend_from_slice(v);
            out.extend_from_slice(b"\r\n");
        }
        out.extend_from_slice(format!("content-length: {}\r\n", resp.body.len()).as_bytes());
        if wants_close {
            out.extend_from_slice(b"connection: close\r\n\r\n");
            out.extend_from_slice(&resp.body);
            let _ = sock.write_all(&out);
            let _ = sock.shutdown(std::net::Shutdown::Write);
            return;
        }
        out.extend_from_slice(b"connection: keep-alive\r\n\r\n");
        out.extend_from_slice(&resp.body);
        if sock.write_all(&out).is_err() {
            return;
        }
    }
}

/// Escapes a Prometheus label value (`"` and `\`).
fn sanitize_label(v: &str) -> String {
    v.replace('\\', "\\\\").replace('"', "\\\"")
}

/// (mtime ns, len) fingerprint of the material files, in fixed order
/// (ca, client_cert, client_key). Absent files/fields stamp as (0, 0).
fn material_stamp(tls: Option<&H3UpstreamTls>) -> Vec<(u128, u64)> {
    let Some(t) = tls else {
        return Vec::new();
    };
    let mut v = Vec::new();
    for p in [
        Some(t.ca.as_str()),
        t.client_cert.as_deref(),
        t.client_key.as_deref(),
    ]
    .into_iter()
    .flatten()
    {
        match std::fs::metadata(p) {
            Ok(m) => {
                let mtime = m
                    .modified()
                    .ok()
                    .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
                    .map(|d| d.as_nanos())
                    .unwrap_or(0);
                v.push((mtime, m.len()));
            }
            Err(_) => v.push((0, 0)),
        }
    }
    v
}

/// Loads the TLS material and assembles the h3 client config.
fn build_client_config(
    tls: Option<&H3UpstreamTls>,
) -> Result<crate::h3_client::H3ClientConfig, String> {
    use rustls::pki_types::pem::PemObject as _;
    let mut cfg = crate::h3_client::H3ClientConfig::default();
    let Some(tls) = tls else {
        return Ok(cfg);
    };
    let cas: Vec<_> = rustls::pki_types::CertificateDer::pem_file_iter(&tls.ca)
        .map_err(|e| format!("ca {}: {e}", tls.ca))?
        .collect::<Result<_, _>>()
        .map_err(|e| format!("ca {}: {e}", tls.ca))?;
    cfg.server_certs = cas;
    cfg.server_name = tls.server_name.clone();
    if let Some(alpn) = &tls.alpn {
        cfg.alpn = vec![alpn.clone().into_bytes()];
    }
    match (&tls.client_cert, &tls.client_key) {
        (Some(cert), Some(key)) => {
            let chain: Vec<_> = rustls::pki_types::CertificateDer::pem_file_iter(cert)
                .map_err(|e| format!("client cert: {e}"))?
                .collect::<Result<_, _>>()
                .map_err(|e| format!("client cert: {e}"))?;
            let key = rustls::pki_types::PrivateKeyDer::from_pem_file(key)
                .map_err(|e| format!("client key: {e}"))?;
            cfg.client_cert = Some(crate::h3_client::ClientCert { chain, key });
        }
        (Some(_), None) | (None, Some(_)) => {
            return Err("h3_tls: client_cert and client_key must be set together".into());
        }
        (None, None) => {}
    }
    Ok(cfg)
}

/// Reason phrase for the common status codes (empty reason is valid
/// h1; the table just keeps responses readable).
fn reason(code: u16) -> &'static str {
    match code {
        200 => "OK",
        201 => "Created",
        202 => "Accepted",
        204 => "No Content",
        206 => "Partial Content",
        301 => "Moved Permanently",
        302 => "Found",
        304 => "Not Modified",
        400 => "Bad Request",
        401 => "Unauthorized",
        403 => "Forbidden",
        404 => "Not Found",
        405 => "Method Not Allowed",
        408 => "Request Timeout",
        409 => "Conflict",
        412 => "Precondition Failed",
        413 => "Payload Too Large",
        415 => "Unsupported Media Type",
        422 => "Unprocessable Entity",
        429 => "Too Many Requests",
        500 => "Internal Server Error",
        501 => "Not Implemented",
        502 => "Bad Gateway",
        503 => "Service Unavailable",
        504 => "Gateway Timeout",
        _ => "Response",
    }
}
